spring.application.name=billetera
spring.datasource.url=jdbc:postgresql://localhost:5433/billetera_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update